BID-18-BE-User-Information-Update
hhe-wtag/bidify pull request #8
Opened 2024-12-22 09:23 UTC by afm-wtag

[BE - User Information Update](https://welltravel.atlassian.net/browse/BID-18?atlOrigin=eyJpIjoiZTUwMWY0MzljMWFjNDEzYWFjYjVhOThkNzhhMDBmNDciLCJwIjoiaiJ9)

**Description**
Added a PUT endpoint `/api/user/profile/update` to allow users to update their profile information, including First Name, Last Name, Contact Number, Address, and Balance.
Updated routing to include the new profile update functionality.

**Endpoint**
PUT /api/user/profile/update
Allows authenticated users to update their profile fields.

**Routing**
Updated routes in the application to include:
app.use('/api/auth', AuthRoutes);
app.use('/api/user', UserRoutes);

**Authentication & Validation**
The endpoint is protected by JWT authentication and validates user inputs.
Returns appropriate error responses for invalid data or unauthorized access.

2024-12-23 08:36 UTC, hhe-wtag requested changes

2024-12-23 08:36 UTC, hhe-wtag commented on backend/src/repositories/BaseRepository.js
> +
Suggestion: `findbyEmail` is a user specific function I would suggest you to keep it in the user repository. Or if we want to remove it, we can have a generic function here like `findByFilter` or `findOne` to pass a variable (filter) like email or id for item to fine one item. 

In #7 I have already made changes to BaseRepository code. Kindly check that PR refactor code.

2024-12-23 16:22 UTC, hhe-wtag commented on backend/src/repositories/BaseRepository.js
> +
Please keep user centric functions to `UserRepository`.

2024-12-23 16:22 UTC, hhe-wtag commented on backend/src/repositories/BaseRepository.js
> +
ditto

2024-12-23 16:22 UTC, hhe-wtag commented on backend/src/models/user.model.js
> -  return bcrypt.compare(candidatePassword, user.password);
The reason that I did this is to not expose the password in the repository functions itself, where we had to remove the users password manually before sending it back to the controller which this PR is implementing. I found it less secure to follow so instead using the `select(+password)` in the repository functions level I used it this method only where it was absolutely needed and this function don't expose the password.

2024-12-23 16:22 UTC, hhe-wtag commented on backend/src/repositories/UserRepository.js
> +    return { newUser, token };
Need to update the name of the property here, changing `user` to `newUser` will change the response body. Please adhere to consistent naming, otherwise the frontend will also need to be refactored. Plus we need to remove the password from the newUser here also.

```js
await newUser.save();

newUser.password = undefined;

const token = await newUser.generateAuthToken();

return { user: newUser, token };
```

2024-12-25 08:37 UTC, afm-wtag commented on backend/src/repositories/UserRepository.js
> +    return { newUser, token };
Update the code

2024-12-25 08:37 UTC, afm-wtag commented on backend/src/models/user.model.js
> -  return bcrypt.compare(candidatePassword, user.password);
secured the password adding user.password=undefined

2024-12-25 08:44 UTC, afm-wtag commented on backend/src/repositories/BaseRepository.js
> +
Updated the code

2024-12-25 09:45 UTC, hhe-wtag approved these changes
Thank you!

2024-12-25 10:01 UTC, merged